site_name: Docs
site_url: https://lasseheia.github.io/docs/

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - content.code.select

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - blog

repo_name: lasseheia/docs
repo_url: https://github.com/lasseheia/docs
